services:
  voltapp1:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5332/volt
      SPRING_DATASOURCE_USERNAME: mohamed
      SPRING_DATASOURCE_PASSWORD: adel
    depends_on:
      - postgres_db
    networks:
        - postgres_db
    restart: unless-stopped
  postgres_db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: adel
      POSTGRES_DB: volt
    volumes:
      - C:/VoltApp:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - postgres_db
    restart: unless-stopped

networks:
  postgres_db:
    driver: bridge
