
CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TABLE IF NOT EXISTS user_management.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,  -- Assuming Role is an ENUM stored as a STRING
    password_hash BYTEA NOT NULL,
    password_salt BYTEA NOT NULL,
    verification_token VARCHAR(255),
    verified_at TIMESTAMP,
    password_reset_token VARCHAR(255),
    reset_token_expires TIMESTAMP
);


CREATE TABLE IF NOT EXISTS user_management.refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL,
    jwt TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT false,
    loggedOut BOOLEAN NOT NULL DEFAULT false,
    user_id UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user_management.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_publication (completion_date timestamp(6) with time zone, publication_date timestamp(6) with time zone, id uuid not null, event_type varchar(255), listener_id varchar(255), serialized_event varchar(255), primary key (id))
